# fly.toml app configuration file generated for dnssecmenot on 2025-06-20T16:13:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dnssecmenot'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.24.2'

[[mounts]]
  source = "data"
  destination = "/data"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
